title: "Murali Venkatraman Data & AI Portfolio"
description: "Portfolio showcasing Azure, Databricks, ADF, Synapse, Power BI, and Data Governance expertise with case studies and sanitized demos."
theme: minima
markdown: kramdown
